
package introsde.health.soap.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "People", targetNamespace = "http://ws.soap.health.introsde/", wsdlLocation = "http://127.0.1.1:6902/ws/people?wsdl")
public class People_Service
    extends Service
{

    private final static URL PEOPLE_WSDL_LOCATION;
    private final static WebServiceException PEOPLE_EXCEPTION;
    private final static QName PEOPLE_QNAME = new QName("http://ws.soap.health.introsde/", "People");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.1.1:6902/ws/people?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PEOPLE_WSDL_LOCATION = url;
        PEOPLE_EXCEPTION = e;
    }

    public People_Service() {
        super(__getWsdlLocation(), PEOPLE_QNAME);
    }

    public People_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PEOPLE_QNAME, features);
    }

    public People_Service(URL wsdlLocation) {
        super(wsdlLocation, PEOPLE_QNAME);
    }

    public People_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PEOPLE_QNAME, features);
    }

    public People_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public People_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns People
     */
    @WebEndpoint(name = "PeopleImplementationPort")
    public People getPeopleImplementationPort() {
        return super.getPort(new QName("http://ws.soap.health.introsde/", "PeopleImplementationPort"), People.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns People
     */
    @WebEndpoint(name = "PeopleImplementationPort")
    public People getPeopleImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soap.health.introsde/", "PeopleImplementationPort"), People.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PEOPLE_EXCEPTION!= null) {
            throw PEOPLE_EXCEPTION;
        }
        return PEOPLE_WSDL_LOCATION;
    }

}
